name: Sync articles from medaffairs-articles

on:
  repository_dispatch:
    types: [medaffairs-articles-updated]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout site repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout medaffairs-articles into subdir
        uses: actions/checkout@v4
        with:
          repository: Nick-PalPark/medaffairs-articles
          token: ${{ secrets.MEDAFFAIRS_ARTICLES_TOKEN }}
          path: medaffairs-articles
          fetch-depth: 1

      - name: Ensure data directory
        run: |
          mkdir -p data

      - name: Copy articles.json into site
        run: |
          SOURCE_FILE="medaffairs-articles/articles.json"
          DEST_FILE="data/articles.json"
          if [ ! -f "$SOURCE_FILE" ]; then
            echo "Source articles.json not found at $SOURCE_FILE"
            exit 1
          fi
          cp "$SOURCE_FILE" "$DEST_FILE"
          echo "Copied $SOURCE_FILE -> $DEST_FILE"

      - name: Commit & push changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/articles.json || true
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync articles.json from medaffairs-articles: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            git push
            echo "Pushed updated data/articles.json"
          fi
