name: Sync articles from medaffairs-articles

on:
  repository_dispatch:
    types: [medaffairs-articles-updated]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout medaffairs.tech
        uses: actions/checkout@v4

      - name: Ensure data dir
        run: mkdir -p data

      - name: Download articles.json (public medaffairs-articles)
        if: ${{ secrets.MEDAFFAIRS_ARTICLES_TOKEN == '' }}
        run: |
          curl -fsSL -o data/articles.json \
            https://raw.githubusercontent.com/Nick-PalPark/medaffairs-articles/main/articles.json

      - name: Download articles.json (private medaffairs-articles)
        if: ${{ secrets.MEDAFFAIRS_ARTICLES_TOKEN != '' }}
        env:
          ARTICLES_TOKEN: ${{ secrets.MEDAFFAIRS_ARTICLES_TOKEN }}
        run: |
          curl -fsSL -H "Authorization: token $ARTICLES_TOKEN" \
            -H "Accept: application/vnd.github.v3.raw" \
            "https://api.github.com/repos/Nick-PalPark/medaffairs-articles/contents/articles.json?ref=main" \
            -o data/articles.json

      - name: Show diff
        run: git --no-pager diff --no-color || true

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Sync articles.json from medaffairs-articles"
          file_pattern: data/articles.json
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"